websites = {
"google":"www.google.com",
"youtube":"www.youtube.com",
"facebook":"www.facebook.com",
"instagram":"www.instagram.com",
"twitter":"www.twitter.com",
"x":"www.x.com",
"linkedin":"www.linkedin.com",
"github":"www.github.com",
"stackoverflow":"www.stackoverflow.com",
"reddit":"www.reddit.com",
"wikipedia":"www.wikipedia.org",
"yahoo":"www.yahoo.com",
"bing":"www.bing.com",
"duckduckgo":"www.duckduckgo.com",
"amazon":"www.amazon.com",
"flipkart":"www.flipkart.com",
"ebay":"www.ebay.com",
"netflix":"www.netflix.com",
"primevideo":"www.primevideo.com",
"hotstar":"www.hotstar.com",
"spotify":"www.spotify.com",
"apple":"www.apple.com",
"microsoft":"www.microsoft.com",
"openai":"www.openai.com",
"chatgpt":"chat.openai.com",
"gmail":"mail.google.com",
"outlook":"outlook.live.com",
"drive":"drive.google.com",
"dropbox":"www.dropbox.com",
"onedrive":"onedrive.live.com",
"slack":"www.slack.com",
"zoom":"www.zoom.us",
"meet":"meet.google.com",
"skype":"www.skype.com",
"discord":"www.discord.com",
"telegram":"web.telegram.org",
"whatsapp":"web.whatsapp.com",
"pinterest":"www.pinterest.com",
"quora":"www.quora.com",
"medium":"www.medium.com",
"devto":"www.dev.to",
"hashnode":"www.hashnode.com",
"freecodecamp":"www.freecodecamp.org",
"coursera":"www.coursera.org",
"udemy":"www.udemy.com",
"edx":"www.edx.org",
"khanacademy":"www.khanacademy.org",
"byjus":"www.byjus.com",
"unacademy":"www.unacademy.com",
"geeksforgeeks":"www.geeksforgeeks.org",
"w3schools":"www.w3schools.com",
"codecademy":"www.codecademy.com",
"hackerrank":"www.hackerrank.com",
"codechef":"www.codechef.com",
"leetcode":"www.leetcode.com",
"atcoder":"www.atcoder.jp",
"codeforces":"www.codeforces.com",
"replit":"www.replit.com",
"glitch":"www.glitch.com",
"vercel":"www.vercel.com",
"netlify":"www.netlify.com",
"heroku":"www.heroku.com",
"aws":"aws.amazon.com",
"azure":"azure.microsoft.com",
"gcp":"cloud.google.com",
"digitalocean":"www.digitalocean.com",
"docker":"www.docker.com",
"kubernetes":"kubernetes.io",
"npm":"www.npmjs.com",
"pypi":"pypi.org",
"wordpress":"www.wordpress.com",
"blogger":"www.blogger.com",
"tumblr":"www.tumblr.com",
"shopify":"www.shopify.com",
"wix":"www.wix.com",
"squarespace":"www.squarespace.com",
"canva":"www.canva.com",
"figma":"www.figma.com",
"dribbble":"www.dribbble.com",
"behance":"www.behance.net",
"unsplash":"www.unsplash.com",
"pexels":"www.pexels.com",
"pixabay":"www.pixabay.com",
"imgur":"www.imgur.com",
"giphy":"www.giphy.com",
"tenor":"www.tenor.com",
"nytimes":"www.nytimes.com",
"guardian":"www.theguardian.com",
"bbc":"www.bbc.com",
"cnn":"www.cnn.com",
"reuters":"www.reuters.com",
"aljazeera":"www.aljazeera.com",
"forbes":"www.forbes.com",
"techcrunch":"www.techcrunch.com",
"wired":"www.wired.com",
"theverge":"www.theverge.com",
"arstechnica":"www.arstechnica.com",
"producthunt":"www.producthunt.com",
"hackernews":"news.ycombinator.com",
"slashdot":"slashdot.org",
"archive":"archive.org",
"imdb":"www.imdb.com",
"rottentomatoes":"www.rottentomatoes.com",
"letterboxd":"www.letterboxd.com",
"goodreads":"www.goodreads.com",
"steam":"store.steampowered.com",
"epicgames":"www.epicgames.com",
"itchio":"www.itch.io",
"twitch":"www.twitch.tv",
"kick":"www.kick.com",
"roblox":"www.roblox.com",
"minecraft":"www.minecraft.net",
"playstation":"www.playstation.com",
"xbox":"www.xbox.com",
"nintendo":"www.nintendo.com",
"ign":"www.ign.com",
"gamespot":"www.gamespot.com",
"speedtest":"www.speedtest.net",
"fast":"fast.com",
"ookla":"www.ookla.com",
"cloudflare":"www.cloudflare.com",
"whois":"www.whois.com",
"godaddy":"www.godaddy.com",
"namecheap":"www.namecheap.com",
"fiverr":"www.fiverr.com",
"upwork":"www.upwork.com",
"freelancer":"www.freelancer.com",
"toptal":"www.toptal.com",
"indeed":"www.indeed.com",
"naukri":"www.naukri.com",
"monster":"www.monster.com",
"glassdoor":"www.glassdoor.com",
"ziprecruiter":"www.ziprecruiter.com",
"paypal":"www.paypal.com",
"stripe":"www.stripe.com",
"wise":"www.wise.com",
"paytm":"www.paytm.com",
"phonepe":"www.phonepe.com",
"gpay":"pay.google.com",
"bhim":"www.bhimupi.org.in",
"irctc":"www.irctc.co.in",
"makemytrip":"www.makemytrip.com",
"goibibo":"www.goibibo.com",
"booking":"www.booking.com",
"airbnb":"www.airbnb.com",
"uber":"www.uber.com",
"ola":"www.olacabs.com",
"zomato":"www.zomato.com",
"swiggy":"www.swiggy.com",
"doordash":"www.doordash.com",
"ubereats":"www.ubereats.com",
"chatgpt":"chat.openai.com",
"canva":"www.canva.com",
"notion":"www.notion.so",
"figma":"www.figma.com",
"capcut":"www.capcut.com",
"removebg":"www.remove.bg",
"photopea":"www.photopea.com",
"pixlr":"www.pixlr.com",
"adobe":"www.adobe.com",
"adobeexpress":"www.adobe.com/express",
"descript":"www.descript.com",
"runway":"www.runwayml.com",
"midjourney":"www.midjourney.com",
"leonardo":"www.leonardo.ai",
"stability":"www.stability.ai",

"grammarly":"www.grammarly.com",
"quillbot":"www.quillbot.com",
"deepl":"www.deepl.com",
"translate":"translate.google.com",

"notebooklm":"notebooklm.google.com",
"bard":"bard.google.com",
"gemini":"gemini.google.com",
"claude":"www.anthropic.com",
"perplexity":"www.perplexity.ai",

"trello":"www.trello.com",
"asana":"www.asana.com",
"clickup":"www.clickup.com",
"monday":"www.monday.com",

"drive":"drive.google.com",
"docs":"docs.google.com",
"sheets":"sheets.google.com",
"slides":"slides.google.com",
"forms":"forms.google.com",
"calendar":"calendar.google.com",

"weebly":"www.weebly.com",
"carrd":"www.carrd.co",
"aboutme":"about.me",

"coursera":"www.coursera.org",
"udemy":"www.udemy.com",
"skillshare":"www.skillshare.com",
"brilliant":"www.brilliant.org",

"geogebra":"www.geogebra.org",
"symbolab":"www.symbolab.com",
"wolframalpha":"www.wolframalpha.com",

"speedtest":"www.speedtest.net",
"fast":"fast.com",
"virustotal":"www.virustotal.com",
"tinyurl":"tinyurl.com",
"bitly":"bitly.com",

"archive":"archive.org",
"wayback":"web.archive.org",

"producthunt":"www.producthunt.com",
"huggingface":"www.huggingface.co",

"itch":"www.itch.io",
"tinkercad":"www.tinkercad.com",

"zillow":"www.zillow.com",
"maps":"maps.google.com",

"weather":"weather.com",
"accuweather":"www.accuweather.com",

"espn":"www.espn.com",
"cricbuzz":"www.cricbuzz.com",
"github":"www.github.com",
"gitlab":"www.gitlab.com",
"bitbucket":"bitbucket.org",

"stackoverflow":"www.stackoverflow.com",
"stackexchange":"stackexchange.com",
"superuser":"superuser.com",

"geeksforgeeks":"www.geeksforgeeks.org",
"w3schools":"www.w3schools.com",
"mdn":"developer.mozilla.org",
"freecodecamp":"www.freecodecamp.org",
"codecademy":"www.codecademy.com",
"tutorialspoint":"www.tutorialspoint.com",
"javatpoint":"www.javatpoint.com",
"programiz":"www.programiz.com",

"leetcode":"www.leetcode.com",
"hackerrank":"www.hackerrank.com",
"codechef":"www.codechef.com",
"codeforces":"www.codeforces.com",
"atcoder":"www.atcoder.jp",
"topcoder":"www.topcoder.com",
"cses":"cses.fi",
"projecteuler":"projecteuler.net",

"replit":"www.replit.com",
"codesandbox":"codesandbox.io",
"stackblitz":"stackblitz.com",
"glitch":"glitch.com",
"jsfiddle":"jsfiddle.net",
"codepen":"codepen.io",

"chatgpt":"chat.openai.com",
"gemini":"gemini.google.com",
"claude":"www.anthropic.com",
"perplexity":"www.perplexity.ai",
"phind":"www.phind.com",

"huggingface":"huggingface.co",
"kaggle":"www.kaggle.com",
"colab":"colab.research.google.com",

"vercel":"vercel.com",
"netlify":"www.netlify.com",
"render":"render.com",
"railway":"railway.app",
"heroku":"www.heroku.com",

"firebase":"firebase.google.com",
"supabase":"supabase.com",
"planetscale":"planetscale.com",

"dockerhub":"hub.docker.com",
"npm":"www.npmjs.com",
"pypi":"pypi.org",
"anaconda":"www.anaconda.com",

"postman":"www.postman.com",
"insomnia":"insomnia.rest",

"regex101":"regex101.com",
"jsonformatter":"jsonformatter.org",
"jsonlint":"jsonlint.com",
"diffchecker":"www.diffchecker.com",

"canva":"www.canva.com",
"figma":"www.figma.com",
"excalidraw":"excalidraw.com",
"drawio":"app.diagrams.net",

"notion":"www.notion.so",
"obsidian":"obsidian.md",
"trello":"trello.com",

"coursera":"www.coursera.org",
"udemy":"www.udemy.com",
"edx":"www.edx.org",
"khanacademy":"www.khanacademy.org",
"mitocw":"ocw.mit.edu",

"linuxjourney":"linuxjourney.com",
"explainshell":"explainshell.com",
"devdocs":"devdocs.io",
"cheatsheets":"cheatsheets.zip",

"roadmap":"roadmap.sh",
"frontendmentor":"www.frontendmentor.io",
"cssbattle":"cssbattle.dev",
"flexboxfroggy":"flexboxfroggy.com",
"gridgarden":"cssgridgarden.com",

"webdev":"web.dev",
"caniuse":"caniuse.com",
"pagespeed":"pagespeed.web.dev",

"speedtest":"speedtest.net",
"gtmetrix":"gtmetrix.com",

"stackoverflowjobs":"stackoverflow.com/jobs",
"wellfound":"wellfound.com",
"linkedin":"www.linkedin.com"
}